# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170530_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='std',
            field=models.CharField(default='DEFAULT VALUE', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='std',
            field=models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school.Grade'),
        ),
    ]
